apiVersion: v1
kind: Service
metadata:
  name: arena-service
  labels:
    app: heroes
spec:
  ports:
    - name: arena-rest
      port: 3333
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arena-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heroes
  template:
    metadata:
      labels:
        app: heroes
    spec:
      containers:
        - name: arena
          image: heroes/arena
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3333
          env:
            - name: eureka.client.service-url.defaultZone
              value: http://registry:1111/eureka/