apiVersion: v1
kind: Service
metadata:
  name: arena
  labels:
    app: arena
spec:
  selector:
    app: arena
  ports:
    - name: arena-rest
      port: 3333
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arena-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arena
  template:
    metadata:
      labels:
        app: arena
    spec:
      containers:
        - name: arena-container
          image: heroes/arena:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3333
          env:
            - name: eureka.client.service-url.defaultZone
              value: http://registry:1111/eureka/