apiVersion: v1
kind: Service
metadata:
  name: camp-service
  labels:
    app: heroes
spec:
  ports:
    - name: camp-rest
      port: 2222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heroes
  template:
    metadata:
      labels:
        app: heroes
    spec:
      containers:
        - name: camp
          image: heroes/camp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2222
          env:
            - name: eureka.client.service-url.defaultZone
              value: http://registry:1111/eureka/