apiVersion: v1
kind: Service
metadata:
  name: camp
  labels:
    app: camp
spec:
  selector:
    app: camp
  ports:
    - name: camp-rest
      port: 2222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camp
  template:
    metadata:
      labels:
        app: camp
    spec:
      containers:
        - name: camp-container
          image: heroes/camp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2222
          env:
            - name: eureka.client.service-url.defaultZone
              value: http://registry:1111/eureka/