apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: heroes
spec:
  ports:
    - name: frontend-rest
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heroes
  template:
    metadata:
      labels:
        app: heroes
    spec:
      containers:
        - name: frontend
          image: heroes/frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: eureka.client.service-url.defaultZone
              value: http://registry:1111/eureka/