apiVersion: v1
kind: Service
metadata:
  name: promoter
  labels:
    app: promoter
spec:
  selector:
    app: promoter
  ports:
    - name: promoter-rest
      port: 4444
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promoter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promoter
  template:
    metadata:
      labels:
        app: promoter
    spec:
      containers:
        - name: promoter-container
          image: heroes/promoter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4444
          env:
            - name: eureka.client.service-url.defaultZone
              value: http://registry:1111/eureka/