apiVersion: v1
kind: Service
metadata:
  name: promoter-service
  labels:
    app: heroes
spec:
  ports:
    - name: promoter-rest
      port: 4444
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promoter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heroes
  template:
    metadata:
      labels:
        app: heroes
    spec:
      containers:
        - name: promoter
          image: heroes/promoter
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4444
          env:
            - name: eureka.client.service-url.defaultZone
              value: http://registry:1111/eureka/