apiVersion: v1
kind: Service
metadata:
  name: registry-service
  labels:
    app: heroes
spec:
  ports:
    - name: registry-rest
      port: 1111
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heroes
  template:
    metadata:
      labels:
        app: heroes
    spec:
      containers:
        - name: registry
          image: heroes/registry
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1111